# Generated by Django 3.2.25 on 2024-08-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizacion', '0006_auto_20240823_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajo', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('fecha_ok', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_pliego', models.PositiveIntegerField()),
                ('medida_ancho', models.FloatField()),
                ('medida_alto', models.FloatField()),
                ('papel', models.CharField(max_length=255)),
                ('terminacion', models.CharField(choices=[('nada', 'Nada'), ('troquel', 'Troquel'), ('laminado', 'Laminado'), ('corte', 'Corte')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('detalle_producto', models.TextField(blank=True, null=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='trabajos.ordentrabajo')),
            ],
        ),
    ]
