# Generated by Django 3.2.25 on 2024-08-12 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_auto_20240807_0309'),
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='empresa',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='OT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cotizacion.presupuesto'),
            preserve_default=False,
        ),
    ]
