# Generated by Django 3.2.25 on 2024-08-25 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0009_alter_presupuesto_fecha_emision'),
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_ok',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='presupuesto',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='presupuesto_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizacion.presupuesto'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
