# Generated by Django 3.2.25 on 2024-08-13 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_auto_20240807_0309'),
        ('trabajos', '0002_auto_20240811_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='OT',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='Orden_trabajo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cotizacion.presupuesto'),
            preserve_default=False,
        ),
    ]
