# Generated by Django 3.2.25 on 2024-09-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0002_auto_20240825_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='presupuesto_original',
        ),
        migrations.RemoveField(
            model_name='productoorden',
            name='orden_trabajo',
        ),
    ]
