# Generated by Django 3.2.25 on 2024-08-14 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_auto_20240807_0309'),
        ('trabajos', '0003_auto_20240812_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_presupuesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizacion.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trabajo_presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajo_productos', to='trabajos.trabajopresupuesto')),
            ],
        ),
    ]
