# Generated by Django 3.2.25 on 2024-09-06 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0010_alter_producto_presupuesto'),
        ('trabajos', '0003_auto_20240905_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='presupuesto_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizacion.presupuesto'),
        ),
        migrations.AddField(
            model_name='productoorden',
            name='orden_trabajo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='trabajos.ordentrabajo'),
            preserve_default=False,
        ),
    ]
