# Generated by Django 3.2.25 on 2024-08-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0004_trabajopresupuesto_trabajoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('nombre_trabajo', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_ok', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trabajo_presupuesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_pliego', models.PositiveIntegerField()),
                ('medida_ancho', models.FloatField()),
                ('medida_alto', models.FloatField()),
                ('papel', models.CharField(max_length=255)),
                ('terminacion', models.CharField(choices=[('nada', 'Nada'), ('troquel', 'Troquel'), ('laminado', 'Laminado'), ('corte', 'Corte')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=0, max_digits=10)),
                ('detalle_producto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trabajo_producto',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='trabajopresupuesto',
            name='original_presupuesto',
        ),
        migrations.RemoveField(
            model_name='trabajoproducto',
            name='trabajo_presupuesto',
        ),
        migrations.DeleteModel(
            name='OrdenTrabajo',
        ),
        migrations.DeleteModel(
            name='TrabajoPresupuesto',
        ),
        migrations.DeleteModel(
            name='TrabajoProducto',
        ),
    ]
