# Generated by Django 3.2.25 on 2024-07-10 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_back_end', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoAdicional',
            new_name='Producto',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='cantidad_pliego',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='medida_alto',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='medida_ancho',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='papel',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='terminacion',
        ),
    ]
