# Generated by Django 3.2.25 on 2024-07-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back_end', '0003_auto_20240710_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='valor',
            field=models.PositiveIntegerField(max_length=8),
        ),
    ]
