# Generated by Django 3.2.25 on 2024-07-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_back_end', '0005_alter_precio_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precios',
        ),
        migrations.AddField(
            model_name='producto',
            name='valor',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
