# Generated by Django 3.2.25 on 2024-07-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_rename_nombre_trabajo_presupuesto_nombre_atencion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='nombre_atencion',
            new_name='nombre_trabajo',
        ),
    ]
