# Generated by Django 3.2.25 on 2024-07-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_rename_nombre_atencion_presupuesto_nombre_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='precios',
            field=models.ManyToManyField(related_name='presupuestos', to='cotizacion.Precio'),
        ),
    ]
