# Generated by Django 3.2.25 on 2024-07-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0004_auto_20240727_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
