# Generated by Django 3.2.25 on 2024-08-24 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0006_auto_20240823_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
