# Generated by Django 3.2.25 on 2024-08-22 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizacion', '0006_auto_20240807_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_cotizacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
