# Generated by Django 3.2.25 on 2024-08-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0007_alter_presupuesto_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='producto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cotizacion.presupuesto'),
        ),
    ]
