# Generated by Django 3.2.25 on 2024-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0007_delete_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='aprobado',
            field=models.BooleanField(),
        ),
    ]
