# Generated by Django 3.2.25 on 2024-08-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0008_auto_20240821_2239'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='presupuesto',
            table='presupuesto',
        ),
    ]
