# Generated by Django 3.2.25 on 2024-09-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0009_alter_presupuesto_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cotizacion.presupuesto'),
        ),
    ]
